descriptor-schema-version: "2.2"
info:
  name: reposter
  version: latest
app:
  cpuarch: x86_64
  env:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    http_proxy: ""
    https_proxy: ""
  resources:
    cpu: 50
    disk: 2
    memory: 64
    network:
    - interface-name: eth0
      ports:
        tcp:
        - "8080"
    profile: custom
  startup:
    rootfs: rootfs.tar
    target:
    - sh
    - start.sh
  type: docker
